version: '3.7'

services:

    nginx:
        build: .
        container_name: nginx
        restart: unless-stopped
        expose:
            - 80
        volumes:
            - app_1_static_volume:/app1/files/static/
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_webgateway"
            - "traefik.http.routers.nginx.entrypoints=web"
            - "traefik.http.routers.nginx.rule=Host(
                `app1.localhost`,
                ) && PathPrefix(`/static`)"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
        networks:
            - nginx_network
            - traefik_webgateway
    
networks:

    traefik_webgateway: 
        external:
          name: traefik_webgateway

    nginx_network:
        driver: bridge
        name: nginx_network

volumes:

    app_1_static_volume:
        external: true
        name: app_1_static_volume

